# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Ubuntu
          - os: ubuntu-latest
            container: null
            c_compiler: gcc
            cpp_compiler: g++
            fortran_compiler: gfortran
            enable_asan: ON

          # Fedora
          - os: ubuntu-latest
            container:
              image: fedora:latest
            c_compiler: gcc
            cpp_compiler: g++
            fortran_compiler: gfortran
            enable_asan: ON

          # macOS
          - os: macos-latest
            container: null
            c_compiler: clang
            cpp_compiler: clang++
            #fortran_compiler: gfortran
            enable_asan: OFF

    steps:
    - uses: actions/checkout@v4
    
    - name: Set build dir
      id: strings
      run: echo "build-output-dir=${{ github.workspace }}/build" >> $GITHUB_OUTPUT
    
    # Ubuntu deps
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest' && matrix.container == null
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran cmake build-essential
    
    # Fedora deps
    - name: Install dependencies (Fedora)
      if: matrix.container != null
      run: |
        dnf update -y
        dnf install -y gcc gcc-c++ gcc-gfortran cmake make git libgomp
    
    # macOS deps
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install gcc fftw cmake libomp 
    
    - name: Show OS
      run: |
        cat /etc/os-release || uname -a
    - name: Check compilers
  
      run: |
       which ${{ matrix.c_compiler }} || true
       which ${{ matrix.cpp_compiler }} || true
       which ${{ matrix.fortran_compiler }} || true
       ${{ matrix.fortran_compiler }} --version || true
    
    - name: Configure CMake
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
          -S ${{ github.workspace }} \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
          -DCMAKE_Fortran_COMPILER=${{ matrix.fortran_compiler }} \
          -DCMAKE_BUILD_TYPE=Release \
          -DENABLE_ASAN=${{ matrix.enable_asan }} \
          -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp" \
          -DOpenMP_C_LIB_NAMES="omp" \
          -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp" \
          -DOpenMP_CXX_LIB_NAMES="omp"    
    
    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }}
    
    - name: Test
      run: ctest --test-dir ${{ steps.strings.outputs.build-output-dir }} --output-on-failure
