# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      # Set up a matrix to run the following 3 configurations:
      # 1. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
      # 2. <Linux, Release, latest Clang compiler toolchain on the default runner image, default generator>
      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
      matrix:
        include:
          # Ubuntu
          - os: ubuntu-latest
            container: null
            c_compiler: gcc
            cpp_compiler: g++
            fortran_compiler: gcc
            enable_asan: ON

          # Fedora
          - os: ubuntu-latest
            container: fedora:latest
            c_compiler: gcc
            cpp_compiler: g++
            fortran_compiler: gcc
            enable_asan: ON
            
          # macOS
          - os: macos-latest
            container: null
            c_compiler: clang
            cpp_compiler: clang++
            fortran_compiler: gcc
            enable_asan: OFF
          
    steps:
    - uses: actions/checkout@v4
    
    - uses: fortran-lang/setup-fortran@v1
      with:
          compiler: ${{ matrix.fortran_compiler }}
    - name: Set build dir
      id: strings
      run: echo "build-output-dir=${{ github.workspace }}/build" >> $GITHUB_OUTPUT
    
    # Ubuntu deps
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest' && matrix.container == null
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran cmake build-essential libftw3-dev
    
    # Fedora deps
    - name: Install dependencies (Fedora)
      if: matrix.container != null
      run: |
        dnf update -y
        dnf install -y gcc gcc-c++ gcc-gfortran cmake make git
    
    # MacOS deps
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install fftw cmake libomp gfortran-14
      
    - name: Show OS
      run: cat uname -a
      
    - name: Configure CMake
      run: >
        cmake 
        -B ${{ steps.strings.outputs.build-output-dir }}
        -S ${{ github.workspace }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_Fortran_COMPILER=${{ matrix.fortran_compiler }}
        #-DCMAKE_EXE_LINKER_FLAGS=-lomp
        #-DCMAKE_BUILD_TYPE=Release
        #-DENABLE_ASAN=${{ matrix.enable_asan == 'ON' && 'Debug' || 'Release' }} 
        -DCMAKE_BUILD_TYPE=${{ matrix.enable_asan == 'ON' && 'Debug' || 'Release' }}
        -DENABLE_ASAN=${{ matrix.enable_asan }}
        
    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release
      # run: cmake --build build --config Release
      
    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --output-on-failure -C Release
